env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  non-irregular-whitespace:
    - off
  no-irregular-whitespace:
    - off
